backend:
  name: github
  repo: abutahir47/voicesoftruth
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Homepage Content"
        name: "home"
        file: "index.html"
        fields:
          - label: "Featured Videos"
            name: "videos"
            widget: "list"
            summary: "{{title}}"
            fields:
              - { label: "Video Title", name: "title", widget: "string" }
              - { label: "YouTube URL", name: "url", widget: "string" }

  - name: "whoweare"
    label: "Who We Are"
    files:
      - label: "Who We Are Page"
        name: "whoweare"
        file: "who-we-are.html"
        fields:
          - label: "Video Section"
            name: "videos"
            widget: "list"
            summary: "{{title}}"
            fields:
              - { label: "Video Title", name: "title", widget: "string" }
              - { label: "YouTube URL", name: "url", widget: "string" }
