name: Update siteContent.json

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update siteContent.json
        run: |
          # Replace this with your actual update logic.
          # For example, you might fetch updated JSON from an API or admin panel.
          # Here, we just echo a simple JSON update for demonstration.
          echo '{"whoWeAre":{"videoUrl":"https://www.youtube.com/embed/ZpVAmWnyc00"}}' > siteContent.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.JSON_UPDATE_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add siteContent.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update of siteContent.json"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/abutahir47/voicesoftruth.git
            git push origin HEAD:main
          fi
